#!/usr/bin/env bash
# Record what produced the baseline, so drift can be detected instead of
# discovered.
#
# The baseline was invalidated once by a change nothing was watching. Source,
# compiler version, flags and link options were all identical to what had been
# recorded, yet the binary differed by 1.5 MB, linked libmvec where the original
# did not, and diverged on 99 of 102 files of one model. What moved was
# underneath all of that: the system runtime libraries.
#
# The lesson is not "also record glibc". It is that a fingerprint listing only
# the things someone thought to name will always miss whatever was not named.
# So this records the checkable facts AND the resolved shared-library set, and
# verify-baseline.sh remains the authority -- a fingerprint tells you what
# changed, but only rebuilding and comparing tells you whether it mattered.
#
# Usage:
#   record-provenance.sh --check      compare the current environment against it
#   record-provenance.sh --capture    write the manifest next to the baseline
#   record-provenance.sh --capture --force   overwrite an existing manifest
#
# Writing requires --capture, and refuses to clobber an existing manifest
# without --force. It used to write on a bare invocation, which is one keystroke
# away from --check and destroys the only record of what produced the baseline:
# the environment fields become today's, and the source fields become the
# refactored tree's instead of the pristine commit's. After that the drift alarm
# compares the present against itself and can never fire again.
#
# That is the same shape as E-05 and E1-01 -- an artifact silently replaced, and
# every later verification measuring the wrong thing while reporting green. A
# reference that the verification depends on must not be overwritable by a
# command whose intent was to read it.

set -uo pipefail
export LC_ALL=C

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

BASELINE_DIR="${MARLIM_BASELINE:-$HOME/marlim3-baseline}"
manifest="$BASELINE_DIR/provenance.txt"
binary="$BASELINE_DIR/bin/Marlim3-baseline"

red=$'\033[0;31m'; green=$'\033[0;32m'; yellow=$'\033[1;33m'; reset=$'\033[0m'

collect() {
    cd "$project_root" || exit 2

    echo "# baseline provenance -- generated by record-provenance.sh"
    echo "captured_at        $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "host               $(uname -srm)"
    echo "distro             $(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME")"
    echo "cpu                $(lscpu | awk -F: '/^Model name/ { gsub(/^ +/, "", $2); print $2; exit }')"
    echo

    echo "source_commit      $(cat "$BASELINE_DIR/commit" 2>/dev/null || echo unknown)"
    echo "sisprod_cpp_sha    $(sha256sum src/core/SisProd.cpp | cut -d' ' -f1)"
    echo "sisprod_h_sha      $(sha256sum src/include/SisProd.h | cut -d' ' -f1)"
    echo "cmakelists_sha     $(sha256sum CMakeLists.txt | cut -d' ' -f1)"
    echo

    echo "compiler           $(gcc --version | head -1)"
    echo "fortran            $(gfortran --version | head -1)"
    echo "cmake              $(cmake --version | head -1)"
    echo "libc               $(ldd --version | head -1)"
    echo

    if [[ -x "$binary" ]]; then
        echo "binary_sha         $(sha256sum "$binary" | cut -d' ' -f1)"
        echo "binary_size        $(stat -c %s "$binary")"
        echo "# resolved shared libraries -- this is what moved the last time the"
        echo "# baseline went stale, and it is not covered by any version string above"
        ldd "$binary" 2>/dev/null | awk '{ print "linked             " $1 }' | sort
    else
        echo "binary_sha         MISSING at $binary"
    fi
}

# The manifest answers two questions whose answers mean opposite things.
#
#   Did the ENVIRONMENT move? That is outside our control and is the D-11
#     signal: a system change once invalidated the baseline while source,
#     compiler, flags and link options all matched what had been recorded.
#
#   Did the SOURCE move? That is the work happening. From stage 1 onward it
#     changes at every stage, by construction.
#
# Comparing them as one blob made the check report CHANGED on every run from
# stage 1 on, with "run verify-baseline.sh before trusting any gate below"
# attached to it. An alarm that fires every time is one the operator learns to
# skip, and this one exists for the rare case where skipping it is expensive.
#
# cmakelists_sha stays on the environment side deliberately: it carries the
# build flags, and -ffp-contract=off living there is exactly the kind of change
# that would invalidate the baseline without touching a line of source.
SOURCE_KEYS='^(source_commit|sisprod_cpp_sha|sisprod_h_sha)'

if [[ "${1:-}" == "--check" ]]; then
    [[ -f "$manifest" ]] || {
        printf '%sno manifest at %s -- run without --check first%s\n' "$red" "$manifest" "$reset" >&2
        exit 2
    }

    current="$(mktemp)"; trap 'rm -f "$current"' EXIT
    collect > "$current"

    # captured_at always differs and says nothing about drift.
    recorded_env="$(mktemp)"; current_env="$(mktemp)"
    recorded_src="$(mktemp)"; current_src="$(mktemp)"
    trap 'rm -f "$current" "$recorded_env" "$current_env" "$recorded_src" "$current_src"' EXIT

    grep -vE "^captured_at|$SOURCE_KEYS" "$manifest" > "$recorded_env"
    grep -vE "^captured_at|$SOURCE_KEYS" "$current"  > "$current_env"
    grep -E "$SOURCE_KEYS" "$manifest" > "$recorded_src"
    grep -E "$SOURCE_KEYS" "$current"  > "$current_src"

    environment_moved=0
    diff "$recorded_env" "$current_env" > /dev/null || environment_moved=1
    source_moved=0
    diff "$recorded_src" "$current_src" > /dev/null || source_moved=1

    if (( environment_moved )); then
        printf '%sPROVENANCE CHANGED since the baseline was captured:%s\n' "$yellow" "$reset"
        diff "$recorded_env" "$current_env" | grep '^[<>]' | sed 's/^/  /'
        if (( source_moved )); then
            printf '%s  (the source also differs, which is expected during refactoring)%s\n' \
                   "$yellow" "$reset"
        fi
        printf '\n%sA change here does not by itself invalidate the baseline, and no change\n' "$yellow"
        printf 'here proves it is still valid. Run verify-baseline.sh to find out --\n'
        printf 'rebuilding and comparing is the only thing that answers the question.%s\n' "$reset"
        exit 1
    fi

    if (( source_moved )); then
        printf '%sPROVENANCE UNCHANGED -- environment identical to the baseline%s\n' "$green" "$reset"
        printf 'The source differs, which is what a refactoring stage is:\n'
        diff "$recorded_src" "$current_src" | grep '^[<>]' | sed 's/^/  /'
        printf 'Equivalence of the built result is what gates 2 and 3 answer; this\n'
        printf 'check only watches the environment underneath them.\n'
        exit 0
    fi

    printf '%sPROVENANCE UNCHANGED since the baseline was captured%s\n' "$green" "$reset"
    exit 0
fi

if [[ "${1:-}" != "--capture" ]]; then
    printf '%sno mode given.%s\n' "$red" "$reset" >&2
    printf '  --check     compare the current environment against the manifest\n' >&2
    printf '  --capture   write the manifest (this REPLACES the drift reference)\n' >&2
    exit 2
fi

if [[ -f "$manifest" && "${2:-}" != "--force" ]]; then
    printf '%srefusing to overwrite %s%s\n' "$red" "$manifest" "$reset" >&2
    printf 'It records what produced the baseline. Replacing it resets the drift\n' >&2
    printf 'reference to the present, so the next --check compares now against now.\n' >&2
    printf 'Recapture only when the baseline itself was recaptured; pass --force.\n' >&2
    exit 2
fi

mkdir -p "$BASELINE_DIR"
collect > "$manifest"
printf '%swrote %s%s\n' "$green" "$manifest" "$reset"
cat "$manifest"
