#!/usr/bin/env bash
# Record what produced the baseline, so drift can be detected instead of
# discovered.
#
# The baseline was invalidated once by a change nothing was watching. Source,
# compiler version, flags and link options were all identical to what had been
# recorded, yet the binary differed by 1.5 MB, linked libmvec where the original
# did not, and diverged on 99 of 102 files of one model. What moved was
# underneath all of that: the system runtime libraries.
#
# The lesson is not "also record glibc". It is that a fingerprint listing only
# the things someone thought to name will always miss whatever was not named.
# So this records the checkable facts AND the resolved shared-library set, and
# verify-baseline.sh remains the authority -- a fingerprint tells you what
# changed, but only rebuilding and comparing tells you whether it mattered.
#
# Usage:
#   record-provenance.sh            write the manifest next to the baseline
#   record-provenance.sh --check    compare the current environment against it

set -uo pipefail
export LC_ALL=C

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"

BASELINE_DIR="${MARLIM_BASELINE:-$HOME/marlim3-baseline}"
manifest="$BASELINE_DIR/provenance.txt"
binary="$BASELINE_DIR/bin/Marlim3-baseline"

red=$'\033[0;31m'; green=$'\033[0;32m'; yellow=$'\033[1;33m'; reset=$'\033[0m'

collect() {
    cd "$project_root" || exit 2

    echo "# baseline provenance -- generated by record-provenance.sh"
    echo "captured_at        $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "host               $(uname -srm)"
    echo "distro             $(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME")"
    echo "cpu                $(lscpu | awk -F: '/^Model name/ { gsub(/^ +/, "", $2); print $2; exit }')"
    echo

    echo "source_commit      $(cat "$BASELINE_DIR/commit" 2>/dev/null || echo unknown)"
    echo "sisprod_cpp_sha    $(sha256sum src/core/SisProd.cpp | cut -d' ' -f1)"
    echo "sisprod_h_sha      $(sha256sum src/include/SisProd.h | cut -d' ' -f1)"
    echo "cmakelists_sha     $(sha256sum CMakeLists.txt | cut -d' ' -f1)"
    echo

    echo "compiler           $(gcc --version | head -1)"
    echo "fortran            $(gfortran --version | head -1)"
    echo "cmake              $(cmake --version | head -1)"
    echo "libc               $(ldd --version | head -1)"
    echo

    if [[ -x "$binary" ]]; then
        echo "binary_sha         $(sha256sum "$binary" | cut -d' ' -f1)"
        echo "binary_size        $(stat -c %s "$binary")"
        echo "# resolved shared libraries -- this is what moved the last time the"
        echo "# baseline went stale, and it is not covered by any version string above"
        ldd "$binary" 2>/dev/null | awk '{ print "linked             " $1 }' | sort
    else
        echo "binary_sha         MISSING at $binary"
    fi
}

if [[ "${1:-}" == "--check" ]]; then
    [[ -f "$manifest" ]] || {
        printf '%sno manifest at %s -- run without --check first%s\n' "$red" "$manifest" "$reset" >&2
        exit 2
    }

    current="$(mktemp)"; trap 'rm -f "$current"' EXIT
    collect > "$current"

    # captured_at always differs and says nothing about drift.
    if diff <(grep -v '^captured_at' "$manifest") <(grep -v '^captured_at' "$current") > /dev/null; then
        printf '%sPROVENANCE UNCHANGED since the baseline was captured%s\n' "$green" "$reset"
        exit 0
    fi

    printf '%sPROVENANCE CHANGED since the baseline was captured:%s\n' "$yellow" "$reset"
    diff <(grep -v '^captured_at' "$manifest") <(grep -v '^captured_at' "$current") \
        | grep '^[<>]' | sed 's/^/  /'
    printf '\n%sA change here does not by itself invalidate the baseline, and no change\n' "$yellow"
    printf 'here proves it is still valid. Run verify-baseline.sh to find out --\n'
    printf 'rebuilding and comparing is the only thing that answers the question.%s\n' "$reset"
    exit 1
fi

mkdir -p "$BASELINE_DIR"
collect > "$manifest"
printf '%swrote %s%s\n' "$green" "$manifest" "$reset"
cat "$manifest"
